coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
    patch:
      default:
        target: 75
ignore:
  - "test/",
  - "inventory_management_system_api/migrations/scripts/*" # ignore migration scripts
