FROM python:3.13.3-alpine3.21@sha256:18159b2be11db91f84b8f8f655cd860f805dbd9e49a583ddaac8ab39bf4fe1a7

WORKDIR /inventory-management-system-api-run

COPY requirements.txt ./
# Copy inventory_management_system_api source files
COPY inventory_management_system_api/ inventory_management_system_api/

RUN set -eux; \
    \
    # Install pip dependencies \
    python -m pip install --no-cache-dir --requirement requirements.txt; \
    \
    # Create loging.ini from its .example file \
    cp inventory_management_system_api/logging.example.ini inventory_management_system_api/logging.ini; \
    \
    # Create a non-root user to run as \
    addgroup -S inventory-management-system-api; \
    adduser -S -D -G inventory-management-system-api -H -h /inventory-management-system-api-run inventory-management-system-api;

USER inventory-management-system-api

CMD ["uvicorn", "inventory_management_system_api.main:app", "--app-dir", "/inventory-management-system-api-run", "--host", "0.0.0.0", "--port", "8000"]
EXPOSE 8000
