services:
  inventory-management-system-api:
    container_name: inventory-management-system-api
    build:
      context: .
      target: dev
    volumes:
      - ./inventory_management_system_api:/app/inventory_management_system_api
      - ./keys/jwt-key.pub:/app/keys/jwt-key.pub
      - ./logging.ini:/app/logging.ini
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - path: ./.env
    depends_on:
      - mongo-db
    network_mode: "host"

  mongo-db:
    image: mongo:7.0-jammy
    container_name: ims-api-mongodb
    entrypoint: mongodb_entrypoint.sh
    volumes:
      - ./mongodb/data:/data/db
      - ./scripts/mongodb_entrypoint.sh:/usr/local/bin/mongodb_entrypoint.sh:ro
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    network_mode: "host"
